#!/command/with-contenv bash

# Exit on error
set -e

echo "Starting Laravel Octane..."

USERNAME=$(id -nu "$PUID")

if [ "${LARAVEL_OCTANE_WATCH:="false"}" == "true" ]; then
    echo "👉 Starting Laravel Octane in watch mode..."

    php "$WEBUSER_HOME"/artisan octane:start --server=frankenphp --host=0.0.0.0 --rpc-port=6001 --port=8000 --watch
else
    php "$WEBUSER_HOME"/artisan octane:start --server=frankenphp --host=0.0.0.0 --rpc-port=6001 --port=8000
fi